name: Update Dummy EPG

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:      # Allows you to run it manually

permissions:
  contents: write

jobs:
  update-epg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Run EPG Generator
        run: python generate_epg.py

      - name: Commit and Force Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Create heartbeat file to ensure there is always a change to commit
          date -u > last_run.txt
          
          # Add the EPG, the ID text list, and the heartbeat file
          git add epg.xml epg_ids.txt last_run.txt
          
          # Commit using amend to keep the repo history from growing infinitely
          # If amend fails (first run), it will perform a standard commit
          git commit --amend -m "Fresh EPG Update: $(date -u)" || git commit -m "Fresh EPG Update: $(date -u)"
          
          # Force push to overwrite the old files with the new ones
          git push --force
